Repository TuiChain/frontend, pull requests merged in 2021-01, with the labels that each got.

#21 Pending loan requests
  web/package-lock.json
  web/package.json
  web/src/App.js
  web/src/components/Header.js
  web/src/components/Toast.js
  web/src/containers/LoanRequest.js
  web/src/containers/admin/LoanRequests.js
  web/src/services/loanrequest.service.js
  web/src/util/countries.js
Labels: enhancement

#32 .env file
  web/.env
  web/src/services/auth.service.js
  web/src/services/loanrequest.service.js
Labels: enhancement

#56 Add CircularProgress animation
  web/src/components/LoadingPageAnimation.js
  web/src/containers/LoanRequest.js
  web/src/containers/authentication/Login.js
  web/src/containers/authentication/Signup.js
  web/src/containers/students/Student.js
Labels: enhancement

#61 Status chip
  web/src/components/Status.js
  web/src/theme.js
Labels: enhancement

#36 Loans management
  web/src/App.js
  web/src/components/NavMenu.js
  web/src/components/Status.js
  web/src/containers/loans/Loans.js
  web/src/containers/loans/ManageLoan.js
  web/src/services/loans.service.js
  web/src/theme.js
Labels: enhancement

#39 Funding loans dashboard
  web/package-lock.json
  web/package.json
  web/src/App.js
  web/src/components/Header.js
  web/src/components/Progress.js
  web/src/components/StudentCard.js
  web/src/containers/students/Student.js
  web/src/containers/students/Students.js
  web/src/services/investment.service.js
  web/src/services/loans.service.js
  web/src/services/user.service.js
  web/src/theme.js
Labels: enhancement

#40 Landing page
  web/package-lock.json
  web/package.json
  web/src/App.js
  web/src/assets/icons/dai-outlined.svg
  web/src/assets/icons/dai-solid.svg
  web/src/assets/icons/ethereum-brands.svg
  web/src/assets/icons/handshake-solid.svg
  web/src/assets/icons/infinity-solid.svg
  web/src/assets/icons/left-quote.svg
  web/src/assets/icons/people-carry-solid.svg
  web/src/assets/images/logo-white.png
  web/src/assets/images/world.jpg
  web/src/assets/images/world.png
  web/src/components/DAI.js
  web/src/components/Header.js
  web/src/components/Layout.js
  web/src/components/NavMenu.js
  web/src/components/Toast.js
  web/src/containers/Dashboard.js
  web/src/containers/Error.js
  web/src/containers/Home.js
  web/src/containers/Landing.js
  web/src/services/investment.service.js
  web/src/services/loans.service.js
  web/src/services/user.service.js
  web/src/theme.js
Labels: enhancement

#83 Submit documents
  web/src/App.js
  web/src/components/NavMenuAdmin.js
  web/src/containers/admin/Documents.js
  web/src/containers/loans/Loan.js
  web/src/containers/loans/ManageLoan.js
  web/src/services/documents.service.js
Labels: enhancement

#92 Fix page break due to metamask
  web/src/App.js
  web/src/components/Header.js
  web/src/containers/loans/LoanRequest.js
Labels: bug

#71 Market
  web/src/App.js
  web/src/components/NavMenu.js
  web/src/components/SpinnerInput.js
  web/src/containers/Dashboard.js
  web/src/containers/Market.js
  web/src/containers/loans/Loans.js
  web/src/services/investment.service.js
  web/src/services/loans.service.js
Labels: enhancement

#99 Periodically update loan page
  web/src/containers/loans/Loan.js
Labels: enhancement

#93 Admin finalize loans
  web/src/App.js
  web/src/components/NavMenu.js
  web/src/components/NavMenuAdmin.js
  web/src/containers/admin/ActiveLoans.js
  web/src/services/loans.service.js
Labels: enhancement

#112 Added items to menu
  web/src/components/NavMenu.js
Labels: bug

#115 Change overflow color
  web/public/index.html
Labels: bug

#131 Buy sell positions
  web/src/components/InvestmentCard.js
  web/src/components/SpinnerInput.js
  web/src/containers/Investments.js
  web/src/containers/loans/Loan.js
  web/src/services/investment.service.js
  web/src/services/loans.service.js
  web/src/services/market-transactions.service.js
  web/src/services/wallet.service.js
Labels: bug, enhancement

#134 Add remove sell position feature
  web/src/App.js
  web/src/components/Header.js
  web/src/components/InvestmentCard.js
  web/src/components/KycButton.js
  web/src/components/Layout.js
  web/src/containers/Investments.js
  web/src/containers/admin/ActiveLoans.js
  web/src/containers/admin/LoanRequests.js
  web/src/containers/loans/Loans.js
Labels: enhancement
